export const get_DriverListForSelect_sucess = 'get_DriverListForSelect_sucess'
export const get_DriverListForSelect_waiting = 'get_DriverListForSelect_waiting'
export const get_DriverListForSelect_failed = 'get_DriverListForSelect_failed'
export const get_DriverListForSelect_error = 'get_DriverListForSelect_error'