export const GET_BaseAddrs_SUCCESS = 'GET_BaseAddrs_SUCCESS'
export const GET_BaseAddrs_FAILED = 'GET_BaseAddrs_FAILED'
export const GET_BaseAddrs_WAITING = 'GET_BaseAddrs_WAITING'
export const GET_BaseAddrs_ERROR = 'GET_BaseAddrs_ERROR'
export const GET_BaseAddrs_SERVICEERROR = 'GET_BaseAddrs_SERVICEERROR'