export const GET_Receives_SUCCESS = 'GET_Receives_SUCCESS'
export const GET_Receives_FAILED = 'GET_Receives_FAILED'
export const GET_Receives_WAITING = 'GET_Receives_WAITING'
export const GET_Receives_ERROR = 'GET_Receives_ERROR'
export const GET_Receives_SERVICEERROR = 'GET_Receives_SERVICEERROR'
