export const GET_CarInfo_SUCCESS = 'GET_CarInfo_SUCCESS'
export const GET_CarInfo_FAILED = 'GET_CarInfo_FAILED'
export const GET_CarInfo_WAITING = 'GET_CarInfo_WAITING'
export const GET_CarInfo_ERROR = 'GET_CarInfo_ERROR'
export const GET_CarInfo_SERVICEERROR = 'GET_CarInfo_SERVICEERROR'