export const PUSH_CarInCommand_SUCCESS = 'PUSH_CarInCommand_SUCCESS'
export const PUSH_CarInCommand_FAILED = 'PUSH_CarInCommand_FAILED'
export const PUSH_CarInCommand_WAITING = 'PUSH_CarInCommand_WAITING'
export const PUSH_CarInCommand_ERROR = 'PUSH_CarInCommand_ERROR'
export const PUSH_CarInCommand_SERVICEERROR = 'PUSH_CarInCommand_SERVICEERROR'
export const RESET_PUSH_CarInCommand = 'RESET_PUSH_CarInCommand'

export const GET_CommandCarList_SUCCESS = 'GET_CommandCarList_SUCCESS'
export const GET_CommandCarList_FAILED = 'GET_CommandCarList_FAILED'
export const GET_CommandCarList_WAITING = 'GET_CommandCarList_WAITING'
export const GET_CommandCarList_ERROR = 'GET_CommandCarList_ERROR'
export const GET_CommandCarList_SERVICEERROR = 'GET_CommandCarList_SERVICEERROR'

export const REMOVE_CommandCar_SUCCESS = 'REMOVE_CommandCar_SUCCESS'
export const REMOVE_CommandCar_FAILED = 'REMOVE_CommandCar_FAILED'
export const REMOVE_CommandCar_WAITING = 'REMOVE_CommandCar_WAITING'
export const REMOVE_CommandCar_ERROR = 'REMOVE_CommandCar_ERROR'
export const REMOVE_CommandCar_SERVICEERROR = 'REMOVE_CommandCar_SERVICEERROR'
export const RESET_REMOVE_CommandCar = 'RESET_REMOVE_CommandCar'

export const Finish_Carry_SUCCESS = 'Finish_Carry_SUCCESS'
export const Finish_Carry_FAILED = 'Finish_Carry_FAILED'
export const Finish_Carry_WAITING = 'Finish_Carry_WAITING'
export const Finish_Carry_ERROR = 'Finish_Carry_ERROR'
export const Finish_Carry_SERVICEERROR = 'Finish_Carry_SERVICEERROR'
export const RESET_Finish_Carry = 'RESET_Finish_Carry'
