export const GET_HomeData_SUCCESS = 'GET_HomeData_SUCCESS'
export const GET_HomeData_FAILED = 'GET_HomeData_FAILED'
export const GET_HomeData_WAITING = 'GET_HomeData_WAITING'
export const GET_HomeData_ERROR = 'GET_HomeData_ERROR'
export const GET_HomeData_SERVICEERROR = 'GET_HomeData_SERVICEERROR' 

export const GET_HomeTaskListMore_SUCCESS = 'GET_HomeTaskListMore_SUCCESS'
export const GET_HomeTaskListMore_FAILED = 'GET_HomeTaskListMore_FAILED'
export const GET_HomeTaskListMore_WAITING = 'GET_HomeTaskListMore_WAITING'
export const GET_HomeTaskListMore_ERROR = 'GET_HomeTaskListMore_ERROR'
export const GET_HomeTaskListMore_SERVICEERROR = 'GET_HomeTaskListMore_SERVICEERROR'