export const GET_TruckList_SUCCESS = 'GET_TruckList_SUCCESS'
export const GET_TruckList_FAILED = 'GET_TruckList_FAILED'
export const GET_TruckList_WAITING = 'GET_TruckList_WAITING'
export const GET_TruckList_ERROR = 'GET_TruckList_ERROR'
export const GET_TruckList_SERVICEERROR = 'GET_TruckList_SERVICEERROR'

export const GET_TruckListMore_SUCCESS = 'GET_TruckListMore_SUCCESS'
export const GET_TruckListMore_FAILED = 'GET_TruckListMore_FAILED'
export const GET_TruckListMore_WAITING = 'GET_TruckListMore_WAITING'
export const GET_TruckListMore_ERROR = 'GET_TruckListMore_ERROR'
export const GET_TruckListMore_SERVICEERROR = 'GET_TruckListMore_SERVICEERROR'