export const GET_DriverCommandList_Success = 'GET_DriverCommandList_Success'
export const GET_DriverCommandList_Failed = 'GET_DriverCommandList_Failed'
export const GET_DriverCommandList_Error = 'GET_DriverCommandList_Error'
export const GET_DriverCommandList_Waiting = 'GET_DriverCommandList_Waiting'
export const GET_DriverCommandList_ServiceError = 'GET_DriverCommandList_ServiceError'